# 26 FEBRUARY ASSIGNMENT

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

The variable list_ is a Python list object that can hold elements of many data kinds, whereas array list is a NumPy ndarray object that can only carry elements of one type.

In [5]:
print("Data type of variable list_ is:", type(list_))
print("Data type of variable array_list is:", type(array_list))

Data type of variable list_ is: <class 'list'>
Data type of variable array_list is: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [10]:
for i in list_:
    print("Data type of element", i, "in list_ is:", type(i))


Data type of element 1 in list_ is: <class 'str'>
Data type of element 2 in list_ is: <class 'str'>
Data type of element 3 in list_ is: <class 'str'>
Data type of element 4 in list_ is: <class 'str'>
Data type of element 5 in list_ is: <class 'str'>


In [9]:
for j in array_list:
    print("Data type of element", j, "in array_list is:", type(j))

Data type of element 1 in array_list is: <class 'numpy.str_'>
Data type of element 2 in array_list is: <class 'numpy.str_'>
Data type of element 3 in array_list is: <class 'numpy.str_'>
Data type of element 4 in array_list is: <class 'numpy.str_'>
Data type of element 5 in array_list is: <class 'numpy.str_'>


Q3. 
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [11]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list after the change.

In [12]:
for i in list_:
    print("Data type of element", i, "in list_ is:", type(i))


Data type of element 1 in list_ is: <class 'str'>
Data type of element 2 in list_ is: <class 'str'>
Data type of element 3 in list_ is: <class 'str'>
Data type of element 4 in list_ is: <class 'str'>
Data type of element 5 in list_ is: <class 'str'>


In [13]:
for j in array_list:
    print("Data type of element", j, "in array_list is:", type(j))

Data type of element 1 in array_list is: <class 'numpy.int32'>
Data type of element 2 in array_list is: <class 'numpy.int32'>
Data type of element 3 in array_list is: <class 'numpy.int32'>
Data type of element 4 in array_list is: <class 'numpy.int32'>
Data type of element 5 in array_list is: <class 'numpy.int32'>


In [14]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

In [17]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
shape = num_array.shape
print("Shape of num_array is:", shape)

Shape of num_array is: (2, 3)


In [16]:
size = num_array.size
print("Size of num_array is:", size)

Size of num_array is: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [18]:
zero_array = np.zeros((3, 3))

print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?


In [19]:
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
